<form action="/action_page.php">
  <fieldset>
    <legend>About this notebook:</legend>
    
   <div class="card">
  <h5 class="card-header">This notebook contains Numpy excercises</h5>
  <div class="card-body">
    <a href="menus" class="btn btn-primary" style="color:white;" >Go somewhere</a>
 </div>

In [4]:
import numpy as np

<div class="alert alert-info" role="alert">
  <b>Problem 1:</b><br>
    Create a 2-dimensional array of size 3 x 4 named x, composed of 4-byte integer elements<br>
</div>

In [24]:
x = np.array([[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]], dtype='int32')

| np.int8 | 1 byte | -128 to 127 |

| np.int16 | 2 byte | -32768 to 32767 |

| np.int32 | 4 byte | -2147483648 to 2147483647 |

| np.int64 | 8 byte | -9223372036854775808 to 9223372036854775807 |

<div class="alert alert-info" role="alert">
  <b>Problem 2:</b><br>
    Store the data type of object a in variable a_data_type
<br>
    a = np.array([1, 2, 3])
</div>

In [27]:
a = np.array([1, 2, 3])

In [28]:
a_data_type = a.dtype

In [29]:
a_data_type

dtype('int64')

<div class="alert alert-info" role="alert">
  <b>Problem 3:</b><br>
    Store the type of object a[0] in variable a0_type
<br>
    a = np.array([1, 2, 3])

</div>

In [32]:
a = np.array([1, 2, 3])

In [33]:
a0_type = type(a[0])

In [34]:
a0_type

numpy.int64

<div class="alert alert-info" role="alert">
  <b>Problem 4:</b><br>
    Store the type of object a in variable a_type
<br>
    a = np.array([1, 2, 3])

    
</div>

In [35]:
a = np.array([1, 2, 3])

In [37]:
a_type = type(a)

In [38]:
a_type

numpy.ndarray

<div class="alert alert-info" role="alert">
  <b>Problem 5:</b><br>
    Using Numpy with one line of code, create an array similar to the one below and store it in the a16  variable.
<br>
<br>
    array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])

</div>

In [45]:
a16 = np.full((6, 3), [- np.inf, np.nan, np.inf])

In [46]:
a16

array([[-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf],
       [-inf,  nan,  inf]])

<div class="alert alert-info" role="alert">
  <b>Problem 6:</b><br>
    Create a 8x3 array with all its elements equal to the "Pytopia"  and then store it in the a15  variable.

<br>
</div>

In [48]:
a15 = np.full([8, 3], 'pytopia')

In [49]:
a15

array([['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia'],
       ['pytopia', 'pytopia', 'pytopia']], dtype='<U7')

<div class="alert alert-info" role="alert">
  <b>Problem 7:</b><br>
    Create a 6x4 array with empty elements and store it in variable a14 .
<br>
    <b>Hint</b> use np.empty()
</div>

In [10]:
a14 = np.empty(shape=(6, 4))

In [11]:
a14

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<div class="alert alert-info" role="alert">
  <b>Problem 8:</b><br>
    Create a 6x4 array with all random elements and store it in variable a13.
<br>
</div>

In [29]:
a13 = np.random.random((6, 4))

In [30]:
a13

array([[0.85010949, 0.20841951, 0.61611204, 0.17196578],
       [0.76944293, 0.77998982, 0.72899548, 0.70705575],
       [0.69421573, 0.89946497, 0.22721601, 0.22881555],
       [0.04915015, 0.62418343, 0.89517162, 0.53945537],
       [0.59795213, 0.95564648, 0.27958797, 0.60930265],
       [0.97383257, 0.94251958, 0.35136693, 0.26910972]])

In [31]:
a13.shape

(6, 4)

<div class="alert alert-info" role="alert">
  <b>Problem 9:</b><br>
    Create a 6x4 array with all one elements and store it in variable a12.
<br>
</div>

In [33]:
a12 = np.ones((6,4))

In [34]:
a12

array([[1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.],
       [1., 1., 1., 1.]])

<div class="alert alert-info" role="alert">
  <b>Problem 10:</b><br>
    Create a 6x4 array with all zero elements and store it in variable a11
<br>
</div>

In [37]:
a11 = np.zeros((6,4))

In [38]:
a11

array([[0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.],
       [0., 0., 0., 0.]])

<div class="alert alert-info" role="alert">
  <b>Problem 11:</b><br>
    A 5×5 array is stored in a variable named z, store the value of the second diameter lower than the main diameter in a variable called a10
<br>
</div>

In [5]:
z = np.random.randint(10, size=(5,5))

In [6]:
z

array([[6, 9, 8, 4, 6],
       [4, 6, 8, 4, 3],
       [8, 4, 6, 5, 1],
       [2, 1, 5, 9, 9],
       [4, 8, 5, 0, 4]])

In [7]:
a10 = np.diag(z, -2)

In [8]:
a10

array([8, 1, 5])

<div class="alert alert-info" role="alert">
  <b>Problem 12:</b><br>
nums = np.array([[1, 2, 3, 4, 5],[6, 7, 8, 9, 10]])<br>
    
#### Print the second row of nums
second_row = #?

#### Print all elements of nums that are greater than six
gt_6 = #?

#### Double every element of nums
nums_dbl = 

#### Replace the third column in nums with a new column that adds 1 to each item in the original column.<br>
</div>

In [33]:
nums = np.array([[1,2,3,4,5], [6,7,8,9,10]])

In [34]:
nums

array([[ 1,  2,  3,  4,  5],
       [ 6,  7,  8,  9, 10]])

In [35]:
second_row = nums[1]
second_row

array([ 6,  7,  8,  9, 10])

In [36]:
gt_6 = nums[nums > 6]
gt_6

array([ 7,  8,  9, 10])

In [37]:
nums_dbl = nums*2
nums_dbl

array([[ 2,  4,  6,  8, 10],
       [12, 14, 16, 18, 20]])

In [40]:
nums[:, 2] = nums[:, 2] + 1
nums

array([[ 1,  2,  5,  4,  5],
       [ 6,  7, 10,  9, 10]])

<div class="alert alert-info" role="alert">
  <b>Problem 13:</b><br>
    Find the average of non-zero elements of a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8]) .
</div>

In [46]:
a = np.array([1, 0, 2, 0, 3, 0, 0, 5, 6, 7, 5, 0, 8])

In [49]:
np.mean(a[np.nonzero(a)])

4.625

In [ ]:
np.mean()

<div class="alert alert-info" role="alert">
  <b>First problem:</b><br>
    Curve grades of Math exam with your desired CURVE_CENTER<br>
    <b>hint:</b> make a random list or array of grades between 0 to 20
</div>

In [4]:
import numpy as np

In [2]:
# create a random numpy array with 56 elements between 0 and 20
math_grades = np.random.randint(0, 21, 56)

In [3]:
def curve_grades(grades: np.ndarray, curve_center: [int, float]):
    """
    curve given grades, with given curve center
    
    :param: grades: a numpy array of grades
    :param: curve_center: an int or float number that will curve grades with it.
    :return: an numpy array
    """
    
    average = grades.mean()
    change = curve_center - average
    
    if change < 0:
        return grades
    else:
        return np.clip((grades + change), a_min=0, a_max=20)

In [4]:
math_grades.mean()

10.357142857142858

In [5]:
grades_after_curve = curve_grades(grades=math_grades, curve_center=15)
grades_after_curve

array([12.64285714, 13.64285714, 20.        , 16.64285714, 20.        ,
       20.        , 19.64285714, 14.64285714, 19.64285714,  7.64285714,
        5.64285714,  4.64285714, 14.64285714,  6.64285714, 10.64285714,
        5.64285714,  4.64285714, 19.64285714,  8.64285714, 10.64285714,
        9.64285714,  4.64285714, 20.        , 10.64285714,  5.64285714,
       20.        ,  4.64285714, 12.64285714, 20.        , 12.64285714,
       18.64285714, 19.64285714,  8.64285714, 16.64285714, 20.        ,
        7.64285714, 20.        , 20.        , 19.64285714, 14.64285714,
       20.        , 12.64285714, 18.64285714, 20.        , 12.64285714,
       15.64285714, 12.64285714, 15.64285714, 17.64285714, 20.        ,
       20.        ,  7.64285714, 20.        , 18.64285714,  8.64285714,
       20.        ])

In [6]:
grades_after_curve.mean()

14.327806122448978

In [9]:
import plotly.graph_objects as go


x0 = math_grades
x1 = grades_after_curve

fig = go.Figure()
fig.add_trace(go.Histogram(x=x0))
fig.add_trace(go.Histogram(x=x1))

# Overlay both histograms
fig.update_layout(barmode='overlay')
# Reduce opacity to see both histograms
fig.update_traces(opacity=0.75)
fig.show()

<div class="alert alert-info" role="alert">
  <b>Problem 2:</b><br>
    Implementing a Maclaurin Series<br>
    <b>hint:</b> $e^x = \sum _{n=0} ^{\infty} \frac{x^n}{n!} = 1 + x + \frac{x^2}{2} + \frac{x^3}{6} + ...$
</div>

In [1]:
from math import factorial

In [12]:
fac = np.vectorize(factorial)

In [13]:
def e_x(x, terms):
    n = np.arange(terms)
    return np.sum((x**n) / fac(n))

In [18]:
e_x(3, 10)

20.06339285714286

<div class="alert alert-info" role="alert">
  <b>Problem 2:</b><br>
    Implementing a Maclaurin Series<br>
    <b>hint:</b> $e^x = \sum _{n=0} ^{\infty} \frac{x^n}{n!} = 1 + x + \frac{x^2}{2} + \frac{x^3}{6} + ...$
</div>

<div class="alert alert-info" role="alert">
  <b>Problem 3:</b><br>
    -------<br>
    <b>hint:</b> ----